/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.mathoperationsapp;

import org.junit.Test;

import com.bridgeabz.mathoperationsapp.MathOperationsApp;

import static org.junit.Assert.*;

public class MathOperationAppTest {
    @Test public void testSomeLibraryMethod() {
        MathOperationsApp classUnderTest = new MathOperationsApp();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
