/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgeabz.mathoperationsapp;

public class MathOperationsApp {
    public boolean someLibraryMethod() {
        return true;
    }
}
