/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgeabz.mathoperationsapp;

@FunctionalInterface
interface IMathFunction{
	int calculate(int a, int b);
	static void PrintResult(int a, int b, String functionName, IMathFunction function ) {
		System.out.println("Result of "+functionName+" is "+ function.calculate(a, b));
		
	}
}

public class MathOperationsApp {
    
	public static void main(String args[]) {
		
		IMathFunction add=(int a, int b)->a+b;
		IMathFunction subtract=(int a, int b)-> a-b;
		IMathFunction divide=(int a, int b)->{
			if(b == 0) return 0;
			return a/b;
		};
		
		IMathFunction.PrintResult(6, 3,"Addition", add);
		IMathFunction.PrintResult(6, 3,"Subtraction", subtract);
		IMathFunction.PrintResult(6, 3,"Division",divide	);
		
	}
}
