/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgeabz.mathoperationsapp;

@FunctionalInterface
interface IMathFunction{
	int calculate(int a, int b);
}

public class MathOperationsApp {
    
	public static void main(String args[]) {
		
		IMathFunction add=(int a, int b)->a+b;
		IMathFunction subtract=(int a, int b)-> a-b;
		IMathFunction divide=(int a, int b)->{
			if(b == 0) return 0;
			return a/b;
		};
		
		System.out.println("Addition: "+ add.calculate(6,3));
		System.out.println("Subtraction: "+ subtract.calculate(6,3));
		System.out.println("Division: "+ divide.calculate(6,3));
		
	}
}
